<?php

namespace ContainerV2mGdEn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CTdaSYZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CTdaSYZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CTdaSYZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'packageRepository' => ['privates', 'App\\Repository\\PackageRepository', 'getPackageRepositoryService', true],
        ], [
            'packageRepository' => 'App\\Repository\\PackageRepository',
        ]);
    }
}
