<?php

namespace ContainerV2mGdEn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCours3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Gy9NUgM.App\Entity\Cours' shared service.
     *
     * @return \App\Entity\Cours
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Gy9NUgM": it references class "App\\Entity\\Cours" but no such service exists.');
    }
}
