<?php

namespace Container5Stl4sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KnEtaVdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KnEtaVd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KnEtaVd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cours' => ['privates', '.errored..service_locator.KnEtaVd.App\\Entity\\Cours', NULL, 'Cannot autowire service ".service_locator.KnEtaVd": it references class "App\\Entity\\Cours" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'cours' => 'App\\Entity\\Cours',
            'doctrine' => '?',
        ]);
    }
}
