<?php

namespace Container5Stl4sc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoursService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.KnEtaVd.App\Entity\Cours' shared service.
     *
     * @return \App\Entity\Cours
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.KnEtaVd": it references class "App\\Entity\\Cours" but no such service exists.');
    }
}
