<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5Stl4sc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5Stl4sc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5Stl4sc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5Stl4sc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5Stl4sc\App_KernelDevDebugContainer([
    'container.build_hash' => '5Stl4sc',
    'container.build_id' => 'c9143505',
    'container.build_time' => 1676993694,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5Stl4sc');
