<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXs1Y2vP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXs1Y2vP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXs1Y2vP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXs1Y2vP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXs1Y2vP\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xs1Y2vP',
    'container.build_id' => '666735a4',
    'container.build_time' => 1677272070,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXs1Y2vP');
