<?php

namespace ContainerXs1Y2vP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_51xLXGfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.51xLXGf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.51xLXGf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
        ], [
            'coursRepository' => 'App\\Repository\\CoursRepository',
        ]);
    }
}
