<?php

namespace ContainerXs1Y2vP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OqrPwRaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OqrPwRa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OqrPwRa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'member' => ['privates', '.errored..service_locator.OqrPwRa.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.OqrPwRa": it references class "App\\Entity\\Member" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'member' => 'App\\Entity\\Member',
        ]);
    }
}
