<?php

namespace ContainerXs1Y2vP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMember2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sv5_jNz.App\Entity\Member' shared service.
     *
     * @return \App\Entity\Member
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.sv5_jNz": it references class "App\\Entity\\Member" but no such service exists.');
    }
}
