<?php

namespace ContainerVZzixbO;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoachService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MFTThrR.App\Entity\Coach' shared service.
     *
     * @return \App\Entity\Coach
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MFTThrR": it references class "App\\Entity\\Coach" but no such service exists.');
    }
}
