<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSbqn8xT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSbqn8xT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSbqn8xT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSbqn8xT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSbqn8xT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sbqn8xT',
    'container.build_id' => 'c4c797e8',
    'container.build_time' => 1676366060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSbqn8xT');
