<?php

namespace ContainerM2j6eIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sv5JNzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sv5_jNz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sv5_jNz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'member' => ['privates', '.errored..service_locator.sv5_jNz.App\\Entity\\Member', NULL, 'Cannot autowire service ".service_locator.sv5_jNz": it references class "App\\Entity\\Member" but no such service exists.'],
        ], [
            'member' => 'App\\Entity\\Member',
        ]);
    }
}
