<?php

namespace ContainerM2j6eIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Sv1woME.App\Entity\Blog' shared service.
     *
     * @return \App\Entity\Blog
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Sv1woME": it references class "App\\Entity\\Blog" but no such service exists.');
    }
}
