<?php

namespace ContainerM2j6eIf;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Er8EsL1.App\Entity\Package' shared service.
     *
     * @return \App\Entity\Package
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Er8EsL1": it references class "App\\Entity\\Package" but no such service exists.');
    }
}
